name: fixer_sdk
description: Get currency rates and convert currencies
version: 1.0.0
repository: https://github.com/LiveUser/fixer_sdk

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  sexy_api_client: ^0.0.6+6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
